### PR TITLE
Export makd F and V env variables by default

### PR DESCRIPTION
**Pull request by mihails-strasuns-sociomantic**

### CODE REVIEW

**Review by nemanja-boric-sociomantic — APPROVED** [review]
LGTM

**Comment by nemanja-boric-sociomantic** [comment]
Hmm, where's the code coverage report? There was some work on it in #230, which is why it didn't got merged in the end.

**Review by leandro-lucarella-sociomantic — CHANGES_REQUESTED** [review]
I think this should be added to `beaver dlang make`, I'm not sure I want to pollute the more general `beaver docker run` with this (I'm quite convinced we shouldn't).

Related to https://github.com/sociomantic-tsunami/beaver/issues/25.

**Comment by mihails-strasuns-sociomantic** [comment]
Do we have any non-D makd projects?

**Comment by leandro-lucarella-sociomantic** [comment]
For now I don't think so, but we might. And I prefer to think about a more general solution to the problem instead of keep adding ad-hoc variables to be automatically exported.

**Comment by mihails-strasuns-sociomantic** [comment]
Ok, updated

**Review by leandro-lucarella-sociomantic — APPROVED** [review]
Can you also add a migration release note to warn users this variable will now be automatically passed to docker too?

**Comment by leandro-lucarella-sociomantic** [comment]
Ouch, this is actually a duplicate of 98fc1a85567107e3a7f7a26fc52f641a9b799ac5 in #1.

**Comment by mihails-strasuns-sociomantic** [comment]
Yes but I don't want to wait until new feature is ready to get a bug fix. Which is why such unrelated things shouldn't be put in the same PR ;)

**Comment by leandro-lucarella-sociomantic** [comment]
This is not a bug fix :)

**Comment by leandro-lucarella-sociomantic** [comment]
> Which is why such unrelated things shouldn't be put in the same PR ;)

True, I'm sorry, but now it is finally merged so I'll close as duplicate :)

**Comment by leandro-lucarella-sociomantic** [comment]
Duplicate of #1

**Pull request closed without merging**
