### PR TITLE
Nothing works

### PR DESCRIPTION
**Pull request by mihails-strasuns-sociomantic**

### CODE REVIEW

**Comment by mihails-strasuns-sociomantic** [comment]
@leandro-lucarella-sociomantic ok, this is probably worst case for "hours wasted per lines of code" in my life >_< I have split bare essentials into this PR - can you maybe hint how to make it work with bash? Is it even possible?

**Review by leandro-lucarella-sociomantic — COMMENTED** [review]
I'm sorry for your loss. I honestly don't know what do you need exactly, but seriously at this point I think it might be easier if you just explain me what you need and maybe I implement it. There is no point in waste your time and increase your misery levels :)

**Comment by leandro-lucarella-sociomantic** [comment]
Because I really don't see why are you doing this convert CLI args to ENV vars, it doesn't look particularly good or beauty to be honest :)

**Comment by leandro-lucarella-sociomantic** [comment]
BTW, if this is blocking you somehow, I suggest copying the bits of beaver that you need to your project and do the rest the way it's easier best for you. Then, with a finished use case, we can see how beaver supports that particular use case.

**Comment by mihails-strasuns-sociomantic** [comment]
> Because I really don't see why are you doing this convert CLI args to ENV vars, it doesn't look particularly good or beauty to be honest :)

> I honestly don't know what do you need exactly, but seriously at this point I think it might be easier if you just explain me what you need and maybe I implement it

Let's talk in Slack

**Pull request closed without merging**
