### PR TITLE
Add llucax (myself) to the FUNDING.yml file

### PR DESCRIPTION
**Pull request by llucax**

### CODE REVIEW

**Review by ibuclaw — APPROVED** [review]

**Comment by llucax** [comment]
Travis seems to be really lazy today...

**Review by joseph-wakeling-frequenz — APPROVED** [review]
LGTM in itself.  Might be worth adding a README note about the fundraising side at some point, just to give context/explanation, but I don't think it necessarily needs to go in this PR.

**Comment by llucax** [comment]
What would you put in it?

**Comment by llucax** [comment]
> LGTM in itself. Might be worth adding a README note about the fundraising side at some point, just to give context/explanation, but I don't think it necessarily needs to go in this PR.

OK, since you approved it anyway I will merge for now and we can add any extra needed clarifications in another PR.

**Pull request merged**
