### PR TITLE
docker run: Allow passing extra options

### PR DESCRIPTION
**Pull request by leandro-lucarella-sociomantic**
Extra options can be passed via the environment variable
`BEAVER_DOCKER_OPTS`.

### CODE REVIEW

**Comment by leandro-lucarella-sociomantic** [comment]
Assigning to v0.1.2 because is a really small change, I want to targe deeper changes to v0.2.0.

**Comment by leandro-lucarella-sociomantic** [comment]
FYI @joseph-wakeling-sociomantic @jens-mueller-sociomantic

**Comment by joseph-wakeling-sociomantic** [comment]
@leandro-lucarella-sociomantic you've already released v0.1.2, shouldn't this be v0.1.3? :-P

**Comment by leandro-lucarella-sociomantic** [comment]
OK, I will auto-merge, release v0.1.3 and move to work in v0.2.0.

**Pull request merged**
