### PR TITLE
Update stored codecov script

### PR DESCRIPTION
**Pull request by mihails-strasuns**

### CODE REVIEW

**Review by leandro-lucarella-sociomantic — APPROVED** [review]

**Comment by leandro-lucarella-sociomantic** [comment]
Feel free to merge if you think this is ready.

**Comment by leandro-lucarella-sociomantic** [comment]
I guess this is a minor version bump as it could break something, but feel also free to update the milestone if you think otherwise.

**Comment by mihails-strasuns** [comment]
I have written codecov support last week about issue with multi-comments we see in ocean. Lets wait until it is resolved in case it needs to be bumped again.

**Comment by leandro-lucarella-sociomantic** [comment]
ping

**Comment by mihails-strasuns** [comment]
No response from codecov :( Please proceed as you see fitting.

**Comment by leandro-lucarella-sociomantic** [comment]
So the issues are with the new version, right? Are we trying to solve anything with this new version or was it just a regular update?

**Comment by mihails-strasuns** [comment]
No, the issue is present right no and doesn't go away with script upgrade - so this is completely unrelated. I was simply waiting in case they fix it and we may need another script update.

**Comment by leandro-lucarella-sociomantic** [comment]
> Are we trying to solve anything with this new version or was it just a regular update?

What about this? If we don't have any issues (solved in newer versions) right now, I prefer not to upgrade to minimize the risk, we are really low on numbers to put down fires right now :)

**Comment by mihails-strasuns** [comment]
Yep, it will solve nothing we know about. Nevermind for now :)

**Pull request closed without merging**
